### ISSUE TITLE
Возможность убрать свечи выходного дня из ответа API

### ISSUE THREAD

**Issue by NikolayXHD** [RussianInvestments/investAPI#100]
В терминале есть настройка, убрать свечи выходного дня, например в лёгком графике.

![image](https://github.com/RussianInvestments/investAPI/assets/12046452/1db2d274-746a-41f3-bdb9-632bc1b0b1fc)

![image](https://github.com/RussianInvestments/investAPI/assets/12046452/d94b5e4b-d3c2-442e-95e1-46ca4a6101d8)

Если убрать галку, свечи AFLT 8го - 10го марта скрыты, как и должно быть.

Судя по документации, в API такой возможности в данный момент нет, а хотелось бы, т.к. не очевиден надёжный способ убрать их самостоятельно, с учётом нюансов календаря выходных.

Как правильно отмечено в [статье Тинкофф про отключение свеч выходного дня](https://www.tinkoff.ru/invest/social/profile/Tinkoff_Terminal/08f4fd8d-5fb6-46f4-a3b8-1250c1d5f689/), некоторым трейдерам желательно их убрать, т.к. они оказывают влияние на инструменты технического анализа.

**Comment by p977ac** [comment]
Добрый день. Реализовано в релизе 1.19

**Comment by NikolayXHD** [comment]
@p977ac Оперативно, впечателяет!
Я правильно понимаю, в следующий релиз [invest-python](https://github.com/RussianInvestments/invest-python) это изменение попадёт автоматически?

**Comment by p977ac** [comment]
В этот раз так совпало, что задача уже готовилась к релизу. Да, со следующим обновлением SDK изменение должно быть, в запросе добавится параметр candleSourceType.

**Comment by olsh** [comment]
Правильно ли понимаю что если параметр не передать то будут возвращаться все свечи включая выходные дни?

**Comment by p977ac** [comment]
@olsh верно, и у свечи в ответе появится признак, сформирована она была по торгам с биржи или от торговли внутри брокера.

**Comment by olsh** [comment]
Может быть стоит добавить такой флаг в запрос подписки на свечи?
https://russianinvestments.github.io/investAPI/marketdata/#subscribecandlesrequest

Сейчас получается будут приходить свечи выходного дня?

**Comment by p977ac** [comment]
В стримах свечи строятся по сделкам. Сейчас там нет сделок выходного дня и, как результат, свечей тоже нет, только биржевые. 
Задача на добавление сделок и свечей по выходным есть, сделано будет как-то также, но по срокам пока не подскажу.
