### ISSUE TITLE
Вопросы к прогнозам метода GetForecast

### ISSUE THREAD

**Issue by FerrusM** [RussianInvestments/investAPI#101]
Возвращаемый класс `GetForecastResponse` содержит консенсус-прогноз (`ConsensusItem`) и список таргет-прогнозов (`TargetItem`'ы), на которых основан консенсус-прогноз.
1. Зачем класс `TargetItem` дублирует данные, содержащиеся в `ConsensusItem`: `uid`, `ticker`, `currency`, `current_price`? Разве они могут не совпадать? Класс `TargetItem` нельзя получить никаким другим методом, кроме `GetForecast`, и только вместе с `ConsensusItem`. Почему бы не убрать лишние поля из класса `TargetItem`?
2. Поле `show_name` в `TargetItem`, можно ли его перенести в `ConsensusItem`, а из `TargetItem` убрать? Тоже, чтобы не возвращать лишние данные.
3. `TargetItem` и `ConsensusItem` содержат поля, которые можно рассчитать: `price_change` и `price_change_rel`. Зачем возвращать данные, которые можно рассчитать из других данных? `price_change = target_price - current_price` или `price_change = consensus - current_price`, `price_change_rel = price_change / current_price`.
4. `ConsensusItem` содержит поля `consensus`, `min_target` и `max_target`, рассчитываемые на основе таргет-прогнозов, которые передаются вместе с консенсус-прогнозом. То есть эти три поля тоже необязательно возвращать - их можно рассчитать.
5. Прогнозы, как правило, делаются на какую-то дату. `TargetItem`'ы содержат дату, в которую они сделаны, но не содержат даты, на которую они сделаны. Если все прогнозы имеют какую-либо дату по умолчанию, например, 12 месяцев, необходимо явно указать это в документации. Если нет, то следует добавить соответствующее поле. `ConsensusItem`'ы не содержат даже дату, в которую был сделан консенсус-прогноз, что тоже можно считать упущением.
6. Возвращаемые классы содержат поле `current_price`. Не очень понятно, зачем оно нужно. Прогнозам не нужно содержать промежуточную информацию, достаточно информации о дате, в которую сделан прогноз и дате, на которую сделан прогноз. Вместо текущей цены логичней было бы возвращать цену в дату прогноза, чтобы можно было отследить её изменение или точность прогноза.
7. Есть ли способ определить все инструменты, по которым есть `GetForecastResponse`? Большинство инструментов не содержат таких прогнозов, поэтому большинство запросов возвращает `GetForecastBy NOT_FOUND 50002`. Если нет, то планируется ли добавление такого метода в будущем?

**Comment by p977ac** [comment]
1. Метод [GetForecastBy](https://russianinvestments.github.io/investAPI/instruments/#getforecastby) в первую очередь возвращает прогнозы инвестдомов, консенсус прогноз в общем случае не гарантирован. Консенсус прогнозы лучше получать методом [GetConsensusForecasts](https://russianinvestments.github.io/investAPI/instruments/#getconsensusforecasts). Убирать данные из  массива targets[] не будем.
2. Продублировать show_name в ConsensusItem можно.
3-4. Рассчитанные данные уже есть в источнике, почему бы их не вернуть.
5. Даты до которой стоится прогноз нет, часто дома пересматривают рекомендации в связи с изменением отчетности компаний, рыночной ситуации и т.д. Прогноз можно считать активным, пока он возвращается в ответе. ConsensusItem строится на основе target, датой консенсуса можно считать последнюю дату таргета.
6. Цену на дату прогноза можно получить методом [GetCandles](https://russianinvestments.github.io/investAPI/marketdata/#getcandles) получив дневную свечу за день.
7. Сейчас такой возможности нет, но в перспективе есть возможность добавить метод получения всех TargetItem.

**Comment by FerrusM** [comment]
> 1. Метод [GetForecastBy](https://russianinvestments.github.io/investAPI/instruments/#getforecastby) в первую очередь возвращает прогнозы инвестдомов, консенсус прогноз в общем случае не гарантирован.

Правильно ли я понимаю, что в ConsensusItem возвращается не консенсус, а среднее по TargetItem'ам? А поле recommendation в ConsensusItem рассчитывается по price_change_rel и поэтому, например, у инструмента TGKA (uid: d74daf58-22c3-4e44-8ada-471e404fb795) рекомендация RECOMMENDATION_BUY когда нет ни одного таргета с такой рекомендацией?

> Консенсус прогнозы лучше получать методом [GetConsensusForecasts](https://russianinvestments.github.io/investAPI/instruments/#getconsensusforecasts). 

Что такое uid в ConsensusForecastsItem? Это же не uid инструмента?

**Comment by p977ac** [comment]
Верно, ConsensusItem - это среднее значение, а не консенсус прогноз.

uid в [GetConsensusForecasts](https://russianinvestments.github.io/investAPI/instruments/#getconsensusforecasts) - ИД консенсус прогноза.
Инструмент можно найти по assetUid через метод FindInstruments или методами GetAssets/GetAssetBy
