### ISSUE TITLE
Появление заявки в списке операций после исполнения

### ISSUE THREAD

**Issue by nonamegithub** [RussianInvestments/investAPI#103]
Через какое время есть смысл вызывать GetOperations(), чтобы наверняка была возвращена исполненная заявка и комиссия по ней?

**Comment by volkov-invest** [comment]
Добрый день, к сожалению нет такого "наверняка".
Для 95 персентиля время обновления обычно не превышает 2-5с,
для 99 персентиля - 10-20 сек, но иногда бывают инциденты, при которых время может измеряться минутами.

И я говорю не о задержках api, а о скорости внутреннего процессинга операций во всем брокере, как самой медленной части брокера. Если вы хотите узнать, исполнилась ли заявка - рекомендую использовать GetOrderState - он отрабатывает гораздо быстрее.
