### ISSUE TITLE
Почему у заблокированных фондов Finex api_trade_available_flag=true ?

### ISSUE THREAD

**Issue by belousov-m** [RussianInvestments/investAPI#104]
Например FXRE FXDE FXUS FXKZ FXRD FXRW FXRW и другие. Если запросить список etf, в ответе по ним - свойство api_trade_available_flag=true. Я видел, что они торгуются на внебиржевом рынке, но создавая заявку через api получаю ошибку:
"post order error: unknown security" - если лимитная,
"Недостаточно заявок в стакане." - если рыночная.

Получается, что инструменты недоступны к торговле через api.

Подскажите, можно ли на этот флаг полагаться, или нужно смотреть на свойство trading_status или смотреть на оба при определении - торгуется инструмент через апи или нет или по finex есть исключение какое-нибудь?

**Comment by volkov-invest** [comment]
Добрый вечер, тут логика следующая:
если api_trade_available_flag = false, то бумага в принципе никак не будет торговаться.
если api_trade_available_flag = true - то это не означает, что она торгуется в данный момент и нужно смотреть на trading_status
