### ISSUE TITLE
Изменение спустя какое-то время операции полученной через GetOperations()

### ISSUE THREAD

**Issue by nonamegithub** [RussianInvestments/investAPI#106]
Имеют ли место быть ситуации описанные в subj?
Есть ли гарантия, что однажды появившаяся операция в списке операций уже не изменится при следующих запросах?
Очень жаль тратить время на пруфы, но очень похоже, что такие ситуации вполне себе возможны и регулярно происходят (в течение дня, как минимум, судя по всему). Если именно так и есть, то есть смысл добавить какое-нибудь поле для понимания, что получена финальная версия операции.

**Comment by nonamegithub** [comment]
Ну че, пораскинул мозгами. Родилась гениальная, как обычно, идея, как получать только новые и изменившиеся с определенного момента времени операции через GetOperations(). Просто добавьте в OperationsRequest еще одно поле, например, updated_from. Дальше надо продолжать??? Не благодарите!

**Comment by nonamegithub** [comment]
Ау, ребята, не спим!!!! В себя поверили что-ли? Похоже совсем не догоняете, из каких денег вы зарплату получаете? В банке, судя по всему, вам не смогли этого объяснить, так я могу это сделать. Сегодня просто [конская задержка по появлению операций](https://github.com/RussianInvestments/investAPI/issues/103) - предложенное мною решению сняло бы головную боль куче народу. Разом решается проблема с получением изменившихся и/или поздно появившихся в истории операций. Не сворачивайте мне кровь, шевелимся!

**Comment by nonamegithub** [comment]
и киньте мне свои цифры в приложение. буду держать вас на короткой дистанции, чтобы работали

**Comment by p977ac** [comment]
Чтобы добавить какое-то поле в API, необходимо, чтобы это поле было в источнике. Проблема с операциями известная и не новая, иногда бывают задержки по независящим от API причинам. Попробуем узнать у коллег, что они могут предложить.

**Comment by nonamegithub** [comment]
Чтооо??? Не позорились бы. А поле updated_At есть у вас в таблицах СУБД???

**Comment by nonamegithub** [comment]
дайте свой номер - вижу полное непонимание и низкую квалификацию. объясню на пальцах, как это делается

**Comment by nonamegithub** [comment]
На всякий случай, объясню еще раз: предложенное мною решение не "вылечит" задержки, как таковые. Оно не для этого. Оно позволит, не перезапрашивая все операции с начала дня, к примеру, получить новые с момента последней полученной, а также измененные с того же момента времени (частично или уже полностью исполненные заявки, комиссии по ним, а так же "потеряшки", типа сегодняшних), причем со временем операции более ранним, чем в запросе. Вроде предельно ясно, не? Зачем это нужно, не надо объяснять?
Не вы ли сами постоянно сетуете на нежелание перегружать инфраструктуру брокера?

**Comment by p977ac** [comment]
> Чтооо??? Не позорились бы. А поле updatedAt есть у вас в таблицах СУБД???

Кажется, вы абсолютно не понимаете, что такое АПИ. АПИ - это Интерфейс, у нас нет СУБД, вернее правильнее будет так: у нас в СУБД только техническая информация. Ваши операции хранятся в другом сервисе, к которому АПИ не имеет никакого отшения. Есть ли у коллег это поле или нет и если ли возможность по нему фильтровать я не знаю.
Если начать слушать других, то диалог будет складываться лучше.

**Comment by p977ac** [comment]
> дайте свой номер - вижу полное непонимание и низкую квалификацию. объясню на пальцах, как это делается

Меня зовут Константин Плешаков, я аналитик команды АПИ.
Мне за свою работу не стыдно, и не перед одним клоуном я трястись не собираюсь.

**Comment by nonamegithub** [comment]
Думаю, Константин, долго вы не продержитесь на этой работе

**Comment by nonamegithub** [comment]
Таких как вы, Константин, перед моими глазами уже вереница здесь прошла. А я здесь подольше всех вас вместе взятых, не смотря ни на что. Подолгу всегда убеждать вашу команду приходится что-то путное и стоящее сделать, все ломаетесь да пургу гоните какую-то. Но потом все равно делаете. Говорит вам это о чем-нибудь?

**Comment by nonamegithub** [comment]
И это сделаете. Делайте скриншот сообщения

**Comment by p977ac** [comment]
> И это сделаете. Делайте скриншот сообщения

Для чего? Вы же настолько расплывчато говорите. Не долго продержусь?... Назовёте дату?

**Comment by nonamegithub** [comment]
На память себе сделайте. После увольнения будете родным и близким с трепетом и гордостью показывать, восторженно приговаривая "Это скриншот сообщения в мой адрес того самого Мастера, что размотал меня"!

**Comment by p977ac** [comment]
> На память себе сделайте. После увольнения будете родным и близким с трепетом и гордостью показывать, восторженно приговаривая "Это скриншот сообщения в мой адрес того самого Мастера, что размотал меня"!

Так что, дата будет? Когда мне позвонят и скажут, что я больше тут не работаю?

**Comment by nonamegithub** [comment]
Это будет увольнение по собственному желанию, если вы еще не поняли

**Comment by p977ac** [comment]
> Это будет увольнение по собственному желанию, если вы еще не поняли

То есть не скоро))))

**Comment by nonamegithub** [comment]
Раз ты пока не увольняешься, Константин, то накину последний штрих к своему Masterpiece, так как не выношу колхоз в любых его проявлениях: просто добавляем статус OPERATION_STATE_MODIFIED к [статусам запрашиваемых операций](https://russianinvestments.github.io/investAPI/operations/#operationstate), слегка дополняем запрос к СУБД, в описалово добавляем текст типа
**OPERATION_STATE_MODIFIED | 4 | Изменена в заданный период | -- | --**
и... все!

**Comment by p977ac** [comment]
> Раз ты пока не увольняешься, Константин, то накину последний штрих к своему Masterpiece, так как не выношу колхоз в любых его проявлениях: просто добавляем статус OPERATION_STATE_MODIFIED к [статусам запрашиваемых операций](https://russianinvestments.github.io/investAPI/operations/#operationstate), слегка дополняем запрос к СУБД, в описалово добавляем текст типа **OPERATION_STATE_MODIFIED | 4 | Изменена в заданный период | -- | --** и... все!

Вы хорошо пишете, если то, о чем вы пишете реализуемо. Апи, где получаются операции, делает запрос в общеброкерский сервис. Решить проблему "легко и просто", как вы предлагаете невозможно только на стороне АПИ. Вопрос к ним закинуть, но если тот сервис нас не поддержит, то мы ничего не сможем предложить.
Вы рассуждаете в рамках идеальной системы, по факту она не всегда такая. Будь у нас фильтр по update, его можно было бы прокинуть.

**Comment by nonamegithub** [comment]
Практически в любой СУБД для каждой записи легко могут быть добавлены (или уже имеются!) timestamps типа createdAt и updatedAt. Поэтому лично я не вижу никаких проблем в нашем случае

**Comment by nonamegithub** [comment]
> но, если тот сервис нас не поддержит, то мы ничего не сможем предложить.

А вот здесь никак нельзя занимать соглашательскую позицию. Давить на них надо будет пока не сдадутся. По своему опыту общения с командой Тинькофф API знаю, что это хоть и очень тяжело, но вполне по силам, даже при небольшом желании. Если важность и ценность этого предложения не будут поставлены под сомнение, то придется твоим коллегам немного поднапрячься. 
Достало меня перезапрашивать по много раз все операции за день, пока баланс не сойдется наконец. Если их пара-тройка десятков, то это одно, а если сотни и тысячи - совсем другое: каждая пишется в локальную БД и обсчитывается в целях учета стоимости имеющихся активов. Про снижение нагрузки на инфраструктуру брокера я уже упоминал

**Comment by nonamegithub** [comment]
Для большего понимания происходящего сейчас в инфраструктуре брокера бардака, приведу пример за сегодня:
часть заявок сегодня появилась в операциях гораздо позже часа, причем часть следующих за ними заявок (при отсутствии предыдущих!) появилась относительно быстро.  В таких случаях приходится врубать аварийный режим и ориентироваться на Тиньковскую кривую средневзвешенную цену

**Comment by nonamegithub** [comment]
А касаемо конкретно вашей команды Tinkoff API могут сказать, что рыба гниет с головы. Для тебя добавлю: но чистят ее с хвоста). Классический пример неуважительного отношения команды как к пользователям API, так и к Банку. [Самые востребованные фичи просто игнорируются](https://github.com/RussianInvestments/investAPI/discussions/95#discussioncomment-8626741). Раньше думал, что из-за обилия поставленных и решаемых командой задач, потом понял, что из-за низкой компетенции.
К тебе, Константин, кстати, тоже есть, точнее будут вопросы. Колхоз в вашем хозяйстве автоматически ведет к костылям в моем идеальном коде. Как-нибудь задам я тебе нехорошие вопросы по структуре Portfolio - сейчас мне не до этого

**Comment by nonamegithub** [comment]
> Мне за свою работу не стыдно

А за работу других участников команды тебе стыдно, или каждый у вас сам по себе? В частности, за руководителя команды, который [пообещал](https://github.com/Tinkoff/investAPI/issues/388#issuecomment-1488345583) более года назад решить уже на самом деле давно решенный вопрос с получением N последних свечей? Подобную дичь он может втирать своему руководству, чтобы подольше продержаться на своем хлебном, как я полагаю, месте, но профессионала невозможно обмануть, так ведь, Константин? Сможешь пойти против его лжи? Если да, то готов вооружить тебя железобетонным пруфом. 

> Кажется, вы абсолютно не понимаете, что такое АПИ

Как я вижу, ты очень хорошо разбираешься в АПИ, и уверен, что без труда выяснишь, почему с EndPointa "https://api-invest-gw.tinkoff.ru/market-data-history/api/public/v1/candles" сам Банк уже много лет получает для своих приложений N-последних свечей, а для пользователей Tinkoff API никак не может сделать ничего подобного. Хватит у тебя духа поинтересоваться у руководителя причиной заволынивания столь элементарного вопроса? 

> и не перед одним клоуном я трястись не собираюсь

или только передо мной ты не собираешься делать этого? 

Был один, в общем то, [неплохой товарищ](https://github.com/SRadyukov) в вашей команде - хоть со скрипом, но [относительно быстро делал под моим контролем свою работу](https://github.com/Tinkoff/investAPI/issues/440), да пропал куда-то. Не удивлюсь, если руководитель твоей команды избавился от него за чрезмерную, по его меркам, производительность труда. Имей это обстоятельство ввиду, если решишься.

**Comment by nonamegithub** [comment]
Константин, доброе утро. Каков ответ коллег по полю UpdatedAt? Не думаю, что для этого нужны часы/дни/недели.

**Comment by nonamegithub** [comment]
Костя, почему отказался на телефонную связь выйти? Не позорь РГГУ, веди себя достойно!

**Comment by p977ac** [comment]
> Константин, доброе утро. Каков ответ коллег по полю UpdatedAt? Не думаю, что для этого нужны часы/дни/недели.

Добавить фильтр не получится.

**Comment by nonamegithub** [comment]
Грош тебе цена после этого, "аналитик". Только я вот не закрываю этот issue - не привык сдаваться без боя) Сейчас уже много кого подключил к вопросу из Банка, надеюсь безнаказанным твое преступное (с профессиональной точки зрения) бездействие, не останется. А чтобы ты еще больше прочувствовал, впредь, после подобных инцидентов, буду выставлять требования Банку о компенсации понесенных убытков, с просьбой их выплат за счет зарплатного фонда вашей серенькой у убогой команды "улиток" и "тормозов" InvestAPI
