### ISSUE TITLE
С этим надо что-то делать. Это ненормально!

### ISSUE THREAD

**Issue by nonamegithub** [RussianInvestments/investAPI#109]
Цитата: "[Если у вас есть потребность перезагрузить историю операций, при повторном запросе операции, рекомендуем старые id операции удалить.](https://russianinvestments.github.io/investAPI/operations_problems/)". Да, потребность есть, причем постоянная. Потому-что заявки появляются в базе операций, когда им вздумается. А вдобавок и order_id еще значение не постоянное, оказывается ("[id операций могут меняться со временем. Не стоит ориентироваться на id операций, как на первичный ключ](https://russianinvestments.github.io/investAPI/operations_problems/)").  Дичь лютая! Банк точно по праву примерил на себя определение "Финтех"? На "Курям на смех", максимум, тянет. На первое время, пока решение с постоянным id не найдете, [выход предложен](https://github.com/RussianInvestments/investAPI/issues/106#issuecomment-2040514859). Делайте и не рассуждайте много, раз сами додуматься не можете.

**Comment by nonamegithub** [comment]
Молчание команды воспринимается мною как выражение полного непонимания, поэтому постараюсь объяснить как джунам:

По своей сути, предлагается реализовать т.н. "**инкрементальный**" (по аналогии с бэкапом) режим работы GetOperations(), при котором происходит получение операций, измененных или созданных с момента предыдущего получения (фиксируется на frontende).  Минусов у способа нет, только плюсы:
1) у пользователя Invest API  отпадет необходимость в постоянной перезагрузке операций в попытках отловить "припозднившиеся", а так же внесенные брокером задним числом, операции
2) у пользователя Invest API отпадет необходимость в предварительном удалении старых операций из-за возможной смены их id (добавьте же, наконец, дополнительное поле с [GUID](https://ru.wikipedia.org/wiki/GUID) в каждую операцию!)
3) у брокера "драматически" снизится нагрузка на инфраструктуру

Предлагаю команде пропустить привычно демонстрируемые ею при рассмотрении моих issues стадии отрицания, гнева, торга, и депрессии и сразу перейти к стадии принятия неизбежного - началу работ по реализации идеи.

**Comment by nonamegithub** [comment]
Не исключаю, что после реализации идеи сойдут на нет (значительно уменьшатся) проблемы высоконагруженной [мастерсистемы операций](https://github.com/RussianInvestments/investAPI/issues/108#issuecomment-2042651391), по причинам, изложенным выше.

**Comment by p977ac** [comment]
На текущий момент сервис операций не поддерживает такой функционал. Просьба завести обращение через официальные каналы связи для переадресации заявки в ответственное подразделение.
