### ISSUE TITLE
Вопрос по OrdersStateStream

### ISSUE THREAD

**Issue by nonamegithub** [RussianInvestments/investAPI#126]
Товарищи разработчики, будьте так любезны, объясните логику работы [недавно запущенного](https://github.com/RussianInvestments/investAPI/releases/tag/v1.21) стрима [OrderStateStream](https://russianinvestments.github.io/investAPI/orders/#orderstatestream).
После создания заявки получаю в стриме два сообщения 'order_state' с интервалом в 80-90 мс:
первое сообщение в order_id возвращает ключ идемпотентности, во втором в order_id уже биржевой номер заявки.
Правильно ли я понял, что в этих двух сообщениях нет ни одного поля, которое позволило бы связать их между собой, как относящиеся к одной и той же заявке?

**Comment by nonamegithub** [comment]
Можете не отвечать, все и так очевидно, в принципе. Такое себе решение... 
Объясняю, как должно было быть сделано по-человечески: в любом сообщении 'order_state' должны присутствовать и order_id (биржевой номер заявки) и order_request_id (ключ идемпотентности), точно так же, как и в ответе [GetOrderState() ](https://russianinvestments.github.io/investAPI/orders/#getorderstate). 
Предвижу, что сейчас команда начнет дружно кивать в сторону [мастерсистемы операций](https://github.com/RussianInvestments/investAPI/issues/108#issuecomment-2042651391) и упрекать меня в непонимании работы [Invest API](https://github.com/RussianInvestments/investAPI/issues/74#issuecomment-2053554298) - мне это все фиолетово. Без подключения ваших коллег к процессу так  и будем натягивать сову на глобус. В добавок, все осложняется тем, как я понял, что ваши коллеги еще более тугие, чем вы.

**Comment by nonamegithub** [comment]
Да. И еще. Почему-то забыли про endpoint: wss://invest-public-api.tinkoff.ru/ws/tinkoff.public.invest.api.contract.v1.OrdersStreamService/OrderStateStream

**Comment by nonamegithub** [comment]
Ау, ребята!? Есть хоть кто-то в команде, кому стыдно, что сырое и непроверенное решение выпустили в продакшн? Я постоянно отмечал, что не понимаю, для кого вы делаете свою работу. Очевидно, что работа идет " в никуда", чисто для галочки, чтобы дожить до очередной получки, а там трава не расти

**Comment by p977ac** [comment]
> Ау, ребята!? Есть хоть кто-то в команде, кому стыдно, что сырое и непроверенное решение выпустили в продакшн? Я постоянно отмечал, что не понимаю, для кого вы делаете свою работу. Очевидно, что работа идет " в никуда", чисто для галочки, чтобы дожить до очередной получки, а там трава не расти

Прочитайте [этот топик](https://russianinvestments.github.io/investAPI/orders_state_stream/), возможно, станет понятнее:

**Comment by nonamegithub** [comment]
Спасибо, прочитал. Указал явно в PostOrder() time_in_force: 'TIME_IN_FORCE_DAY' - в сообщениях стрима появился order_request_id, хотя time_in_force при этом возвращается уже как 'TIME_IN_FORCE_UNSPECIFIED' - ну да ладно, переживу.
В топике не увидел не слова, почему при выставлении заявки прилетает аж два сообщения со статусом 'EXECUTION_REPORT_STATUS_NEW' - первое, похоже еще до создания на бирже, с order_id в формате UID, в второе уже с order_id от биржи. Могу без проблем проигнорировать его - мне не трудно, но вдруг у команды и на этот случай есть объяснение. Далее, будет совсем не лишним, если сделаете [здесь](https://russianinvestments.github.io/investAPI/orders/#orderstatestream) гиперссылку на ["этот топик"](https://russianinvestments.github.io/investAPI/orders_state_stream/) - не все здесь внуки Ванги, тем более[ здесь ни слова](https://russianinvestments.github.io/investAPI/orders/#timeinforcetype) о том, что при невыбранном значении не будет полноценно работать [OrderStateStream](https://russianinvestments.github.io/investAPI/orders/#orderstatestream).

**Comment by p977ac** [comment]
> Спасибо, прочитал. Указал явно в PostOrder() time_in_force: 'TIME_IN_FORCE_DAY' - в сообщениях стрима появился order_request_id, хотя time_in_force при этом возвращается уже как 'TIME_IN_FORCE_UNSPECIFIED' - ну да ладно, переживу. В топике не увидел не слова, почему при выставлении заявки прилетает аж два сообщения со статусом 'EXECUTION_REPORT_STATUS_NEW' - первое, похоже еще до создания на бирже, с order_id в формате UID, в второе уже с order_id от биржи. Могу без проблем проигнорировать его - мне не трудно, но вдруг у команды и на этот случай есть объяснение. Далее, будет совсем не лишним, если сделаете [здесь](https://russianinvestments.github.io/investAPI/orders/#orderstatestream) гиперссылку на ["этот топик"](https://russianinvestments.github.io/investAPI/orders_state_stream/) - не все здесь внуки Ванги, тем более[ здесь ни слова](https://russianinvestments.github.io/investAPI/orders/#timeinforcetype) о том, что при невыбранном значении не будет полноценно работать [OrderStateStream](https://russianinvestments.github.io/investAPI/orders/#orderstatestream).

По первому сообщению в стриме есть объяснение в том же топике:
**Сообщения стрима**
**Статусы**
Первое сообщение по поручению в стриме соответствует получению заявки брокером. На этом этапе еще не определен биржевой номер заявки, в _order_id_ передается внутренний номер.

По 'TIME_IN_FORCE_UNSPECIFIED' - есть нюанс, знаем, из-за особенностей протокола не можем отличить TIME_IN_FORCE_UNSPECIFIED от TIME_IN_FORCE_DAY, другие типы мапятся верно. 

 [Здесь](https://russianinvestments.github.io/investAPI/orders/#orderstatestream) страница формируется автоматически из контрактов, ссылку сделаем чуть позже.

**Comment by p977ac** [comment]
(Ссылка)[https://russianinvestments.github.io/investAPI/orders/#orderstatestream] на статью добавлена
