### ISSUE TITLE
Необходима возможность запрашивать через GetCandles() определенное количество свечей

### ISSUE THREAD

**Issue by nonamegithub** [RussianInvestments/investAPI#128]
Раз уж сегодня заметна необычайная активность команды, озвучу [самый востребованный запрос пользователей API](https://github.com/Tinkoff/investAPI/issues/262) еще раз : когда же, наконец, дождемся реализации возможности запрашивать через GetCandles() определенного количества свечей? [Было обещано более года назад](https://github.com/Tinkoff/investAPI/issues/388#issuecomment-1488345583), при всем при том, что делать-то ничего и не надо - все давно [сделано у коллег](https://github.com/RussianInvestments/investAPI/issues/106#issuecomment-2041314898). Попрошу [больше не игнорировать](https://github.com/RussianInvestments/investAPI/discussions/95#discussioncomment-8626741).

**Comment by volkov-invest** [comment]
Фичу запланировали в версии 1.24

**Comment by olsh** [comment]
Вышла версия 1.27, фичи нет. 
Может быть, не стоит закрывать ишью наперед?)
