### ISSUE TITLE
Нужна маркетдата с данными рынков

### ISSUE THREAD

**Issue by nonamegithub** [RussianInvestments/investAPI#139]
Есть необходимость получать маркетдату типа той, что есть в терминале при поиске по тикеру с фильтром "Рынки". Прошу внедрить в Invest API. В частности, imoex и imoex2 интересуют

**Comment by volkov-invest** [comment]
Добрый день, уже есть: https://russianinvestments.github.io/investAPI/head-instruments/#_13

**Comment by nonamegithub** [comment]
Правильно ли я понял, что данные не стримятся, как в терминале?

**Comment by nonamegithub** [comment]
@volkov-invest Александр, сколько команде нужно времени, чтобы начать стримить индексы? С учетом того, что брокер давно уже реализовал и использует этот механизм (я про терминал). Ознакомьтесь в терминале, чтобы понять о чем я говорю.
