### ISSUE TITLE
Пять лет на реализацию востребованного функционала это нормально?

### ISSUE THREAD

**Issue by nonamegithub** [RussianInvestments/investAPI#146]
Ноябрь 2020: [Хотелось бы, чтобы в OpenAPI была возможность зарегистрировать свой Webhook, на который приходили бы уведомления о завершённых ордерах, или же получать уведомления по WebSocket.](https://github.com/Tinkoff/invest-openapi/issues/384)
Апрель 2024: [Добавлен новый стрим состояний ордеров - OrdersStateStream](https://github.com/RussianInvestments/investAPI/releases/tag/v1.21)

Вы серьезно???
И  так вот годами внедряются очень многие востребованные пользователями API предложения. Похоже Волков себе до самой пенсии расписал бэклог ненапряжной работы.

**Comment by nonamegithub** [comment]
А может просто ты не тянешь, Александр, и "давай, до свидания"? Будь добр, ответь, почему ты считаешь, что заслуженно занимаешь свою должность? Постараюсь тебя убедить в обратном - уверен, у меня это получится.

**Comment by nonamegithub** [comment]
Парни, обращаюсь к тем, кто был в числе лайкнувших в 2020 году [это предложение](https://github.com/Tinkoff/invest-openapi/issues/384):  есть тот, кто дождался в 2024 году реализации этой фичи, кроме меня? Проставьте любую эмодзи под этим постом - проведем перекличку оставшихся в строю.
А теперь смотрите, Александр, сколько человек так и не дождалось реализации этого функционала, вместо которого вы внедряли всякую шляпу... Вот на этом вы и едете, Александр, все это время, особо не утруждая себя: "Либо ишак умрет, либо падишах"

**Comment by nonamegithub** [comment]
Ну а чтобы вы поняли, [Александр](https://github.com/volkov-invest) и [Константин](https://github.com/p977ac), почему к вам такое отношение с моей стороны, объясню:
после вот этого ничем неподпруфленного ["вспука"](https://github.com/RussianInvestments/investAPI/issues/108#issuecomment-2042651391) (мягче определения не нахожу, извините), вы собственными руками вычеркнули себя из списков айтишников, окончательно и бесповоротно, даже без права заправлять картриджи. Допускаю, что в действительности вы не настолько отмороженные с профессиональной точки зрения, а вами двигало лишь желание не заморачиваться в лишний раз какой-либо работой, но по итогу это ничего не меняет. Вопросы?

Не уверен, что в банке в должной мере осознают некомпетентность и изворотливость вашей команды...

**Comment by volkov-invest** [comment]
Ранее тебя не банил только потому, что некоторые пожелания были дельными, но ты уже все рамки перешел.
По существу отвечу тут один раз. 

1. Нельзя в API сделать новый стриминг, пока внутренние системы брокера его не поддерживают. Аналогично с любой другой доработкой. Доработка API почти всегда означает необходимость доработок и многих внутренних систем. 

2. Приоритеты. Исправление архитектурных проблем брокера, которые нельзя решить на уровне API, может стоить очень дорого. А тогда возникает вопрос - какой профит это даст Банку? Коллегам нужно тратить полгода и менять архитектуру хранения операций, потому что так захотел какой-то клоун?)

3. Апи и так скрывает архитектурные костыли брокера, давая пользователям понятный и единообразный интерфейс.

А вообще задумайся:  команда сама, по своей инициативе заводит неофициальные тг чаты, хитхабы и пр., чтобы консультировать клиентов и получать обратную связь. И добавляет ли такое клоунское поведение некоторых неуравновешенных персонажей желания решать их вопросы и внедрять их единичные запросы? Ответ очевиден.
