### ISSUE TITLE
Официальный js sdk

### ISSUE THREAD

**Issue by vitalets** [RussianInvestments/investAPI#149]
Привет! 
Когда-то в рамках конкурса от Тинькоф я сделал JS SDK [tinkoff-invest-api](https://github.com/vitalets/tinkoff-invest-api). Сейчас оно существенно отстает от текущих proto-файлов, и поступают запросы от пользователей про новые поля ([раз](https://github.com/vitalets/tinkoff-invest-api/issues/19), [два](https://github.com/vitalets/tinkoff-invest-api/issues/21)).
Обновление на свежие proto-файлы потребует некоторого кол-ва времени и сил. 
Отсюда вопрос - может у вас есть инфа по планам насчет официального js sdk? Чтобы мне не тратить время зря.
Спасибо :)

**Comment by volkov-invest** [comment]
Во-первых, благодарю за работу над неофициальным sdk.

формально официальный есть - https://github.com/RussianInvestments/invest-js, но пока некому им заниматься, там почти нет примеров и поддерживается он только на уровне обновления контрактов.


Вы в issues написали
> По-хорошему бы обновиться на свежую версию, но там много breaking changes

уточните плз, какие изменения ломали код?

**Comment by vitalets** [comment]
Понятно, спасибо!

> уточните плз, какие изменения ломали код?

Я помню, что делал уже один заход - там были изменения, что наравне с figi добавился uid, и это сложно было подружить с тайпскриптом, он требовал оба поля. С точки зрения proto-файлов возможно оно и не breaking, но на стороне sdk требует изменений. 
Я попробую еще раз обновиться и заведу отдельные issue здесь если что.

**Comment by volkov-invest** [comment]
Спасибо!
