### ISSUE TITLE
Передавать события создания и отмены ордеров в поточном gRPC

### ISSUE THREAD

**Issue by p977ac** [RussianInvestments/investAPI#15]
По обращению от @sorc1 

Метод TradesStream не отдаёт указанных событий. Выставляю лимитную заявку,- TradesStream ничего не отдаёт. Удаляю заявку, - аналогично. При этом в GetOrders заявку видно.

Получается, сейчас можно выкручиваться так:

- Периодически мониторить GetOrders, исчезнувшие заявки без событий в TradesStream считать отменёнными (или считать их частично исполненными, если в TradesStream было не всё количество). Но так пропустим заявки, которые поставили и отменили между вызовами GetOrders
- Периодически мониторить GetOperations. Но в операциях не возвращается order_id, так что сопоставить их с заявками проблематично.

Чтобы 2 раза не вставать: хотелось бы видеть account_id в сообщениях OrderState и OrderTrades, иначе при наличии нескольких счетов непонятно как чужие события отфильтровывать. Кстати, если у меня api-ключ сделан только для одного счета, я ведь не буду получать события TradesStream для других счетов? В документации просто сказано, что в потоке будут события от всех счетов.

**Комментарии**
1. TradesStream транслирует только выполненные сделки по вашим ордерам, событий отмены или реджекта в этом стриме нет.

На второй вопрос ответим позже

2. Исходный вопрос был не про TradesStream, а вообще про возможность получения событий новых и отменённых ордеров.
Ещё могут возникать неудобства в связи с ошибками, возвращаемыми TradesStream (или просто с развывом коннекта). В этом случае после реконнекта надо как-то найти все события, прошедшие за это время.

Хотелось бы иметь возможность видеть все ордера в GetOrders, за определенный интервал времени. А не только активные. Или нужна возможность получать order_id в GetOperations.

3. По первоначальному вопросу, кажется, не был получен ответ. Планируется ли поточный интерфейс получения изменений статусов ордеров?

**Comment by ivan-volnov** [comment]
Поддерживаю. Нужен OrdersStream, который транслирует информацию о статусе ордеров. И метод для получения этой же информации на старте при включении или реконнекте. Так сказать добавить информацию о неактивных ордерах в GetOrders (или добавить новый метод).

На данный момент приходится периодически запрашивать GetOrders и GetOperations и неким эвристическим способом пытаться понять те ли ордера выставлены на бирже, что мы ожидаем или не те. А ордера время от времени "теряются"...

**Comment by ivan-volnov** [comment]
При этом использовать GetOrderState имхо считаю очень дорого. Заявок много и тратить лимиты на опрос каждой смысла нет.

**Comment by p977ac** [comment]
@sorc1, @ivan-volnov ,
OrderStream планируется.
Если говорить об информации на старте: GetOrders возвращает список активных, разница между всеми ордерами и активными - исполненные или отмененные ордера. Если сами не отменяли (а биржа отменяет только по окончании сессии, непредвиденных ситуациях или перерывах в торгах, но тогда снимаются все заявки по инструменту), то ордер исполнился. Такая логика разве не работает?

**Comment by ivan-volnov** [comment]
Если в ответе GetOrders нет ордера, который выставлял клиент то это может значить:
1. Ордер по какой-то причине не был выставлен или исполнился
2. Ордер еще в пути от клиента до биржи
Если же в ответе GetOrders есть ордер но не тот что мы ожидали то все еще хуже..
Нам нужно проверить что именно стало с ордером который за которым мы следим и выяснить не появилось ли лишних ордеров о которых мы даже не знаем.

**Comment by ivan-volnov** [comment]
На старте GetOrders хватает но приходится использовать его для переодического опроса состояния заявок

**Comment by p977ac** [comment]
Стрим заявок реализован, есть [правила](https://russianinvestments.github.io/investAPI/orders_state_stream/) для работы со стримом, с которыми рекомендую ознакомится.
