### ISSUE TITLE
TKVM цена закрытия\посденей сделки\ордера?

### ISSUE THREAD

**Issue by WhiteRj** [RussianInvestments/investAPI#151]
Добрый день

По активу TKVM пытаюсь получить ту же цену что отображается вот здесь 
https://www.tbank.ru/invest/etfs/TKVM/

Попробовал 3 разных апи
MarketDataService/GetLastPrices
MarketDataService/GetOrderBook
MarketDataService/GetClosePrices

Ни один из них не отдаёт ту же цену что UI брокера.

Как её получить?

**Comment by volkov-invest** [comment]
для TKVM идентификатор инструмента - "f1a92642-940f-491f-83c8-6fbf8159a37f".
По нему поверил через GetLastPrice - возвращается корректно:
 
     "price": {
        "units": "5",
        "nano": 740000000
      },

**Comment by WhiteRj** [comment]
Добрый день.

Почему тогда позиция в портфеле с этим активом имеет другой инструмент ид? 
4a3a4481-e108-40b7-bf33-69b3406aa282
