### ISSUE TITLE
GRNT и otc_flag и liquidity_flag

### ISSUE THREAD

**Issue by olsh** [RussianInvestments/investAPI#152]
Тикер `GRNT` имеет флаг `otc_flag == true`, но при этом торгуется на внебиржевом рынке.
https://www.tbank.ru/invest/help/educate/otc/about/rus-shares/

При этом из этой же документации следует, что такие бумаги имею низкую ликвидность, но у `GRNT` флаг `liquidity_flag` тоже `true`.

Это ошибка или otc_flag и liquidity_flag работают по-другому?

**Comment by volkov-invest** [comment]
Насколько я знаю, логика формирования liquidity_flag зависит от среднесуточного объема торгов, но не зависит от otc_flag. Лучше этот вопрос задать в ТП

**Comment by olsh** [comment]
Что по первой части вопроса? Меня она больше волнует, этот критерий не такой расплывчатый

> Тикер GRNT имеет флаг otc_flag == true, но при этом торгуется на внебиржевом рынке.
> https://www.tbank.ru/invest/help/educate/otc/about/rus-shares/

**Comment by p977ac** [comment]
Инструмент торгуется в режиме внебиржевой торговли на Московской бирже, такие инструменты не маркируются как OTC. Список получить можно по exchange = otc_ncc.
https://russianinvestments.github.io/investAPI/markets/#_7
На сколько я знаю, от otc_flag в общем отказываются, и сейчас даже ЗПИФ, которые торгуются на внутреннем рынке не помечены как OTC, поэтому классифицировать лучше по торговым площадкам.

Признак ликвидности рассчитывается на основании объемов торгов по инструментам, это некий синтетический показатель.

**Comment by olsh** [comment]
> На сколько я знаю, от otc_flag в общем отказываются, и сейчас даже ЗПИФ, которые торгуются на внутреннем рынке не помечены как OTC, поэтому классифицировать лучше по торговым площадкам.

Понял, наверное, есть смысл пометить флаг как deprecated или в комментарии к нему что-то про это написать.
