### ISSUE TITLE
Order исполняется по нереальной цене в sandbox

### ISSUE THREAD

**Issue by Rosso-corsa** [RussianInvestments/investAPI#154]
Привет!

В sandbox окружении order с id `c3fed34f-d9cc-4bbd-95a9-b5524b4a32d9` на покупку 45 акций MVID исполнился по цене 128.9 за штуку (2024-08-27 19:01:13 GMT+3). Хотя никаких подобных цен на бирже не было, там интервал сделок 116.8-117.1 (до вечерних торгов + первая минута вечерних торгов).

```
{
	"orderId": "c3fed34f-d9cc-4bbd-95a9-b5524b4a32d9",
	"executionReportStatus": "EXECUTION_REPORT_STATUS_FILL",
	"lotsRequested": "45",
	"lotsExecuted": "45",
	"initialOrderPrice": {
		"currency": "rub",
		"units": "5800",
		"nano": 500000000
	},
	"executedOrderPrice": {
		"currency": "rub",
		"units": "5800",
		"nano": 500000000
	},
	"totalOrderAmount": {
		"currency": "rub",
		"units": "5800",
		"nano": 500000000
	},
	"averagePositionPrice": {
		"currency": "rub",
		"units": "128",
		"nano": 900000000
	},
	"initialCommission": {
		"currency": "rub",
		"units": "2",
		"nano": 900250000
	},
	"executedCommission": {
		"currency": "rub",
		"units": "2",
		"nano": 900250000
	},
	"figi": "BBG004S68CP5",
	"direction": "ORDER_DIRECTION_SELL",
	"initialSecurityPrice": {
		"currency": "rub",
		"units": "128",
		"nano": 900000000
	},
	"stages": [],
	"serviceCommission": {
		"currency": "rub",
		"units": "0",
		"nano": 0
	},
	"currency": "rub",
	"orderType": "ORDER_TYPE_LIMIT",
	"orderDate": "2024-08-27T16:01:13.315023Z",
	"instrumentUid": "cf1c6158-a303-43ac-89eb-9b1db8f96043",
	"orderRequestId": ""
}
```

**Comment by Rosso-corsa** [comment]
Проблема регулярная, повторилась, например, с orderId: `32f3cb3e-50b3-4e3c-851d-c77e2d9c92c4` и `f1fbaa61-8b58-4746-bcc8-ca3e96d35678`

**Comment by p977ac** [comment]
Все эти ордера исполнены во время проведения аукциона (19:00-19:05). Песочница устроена достаточно просто: при подаче заявки проверяются bid\ask по стакану (в зависимости от направления) и, если есть в стакане встречное предложение, заявка исполняется. Дело в том, что во время аукциона передается искаженный перевернутый стакан (запросите orderbook в указанный период времени), где спрос ниже предложения. В песочнице нет проверки на это и заявка исполняется.

**Comment by Rosso-corsa** [comment]
@volkov-invest, здравствуйте! Поведение было исправлено?

Я понимаю, что проблема актуальна только во время проведения аукциона, при этом, на мой взгляд, её надо исправить.
