### ISSUE TITLE
Ложное значение признака внебиржевой бумаги otc_flag, за которую огромная комиссия.

### ISSUE THREAD

**Issue by NikolayXHD** [RussianInvestments/investAPI#155]
Согласно [документации о внебиржевых бумагах](https://www.tbank.ru/invest/help/educate/otc/about/rus-shares/?internal_source=app_inv/), комиссия по внебиржевым ценным бумагам в 10 раз выше обычной 0.5% вместо 0.05%

![image](https://github.com/user-attachments/assets/f8ea5506-d76e-4c0c-8242-bb06e19c985a)

В [документации API](https://tinkoff.github.io/investAPI/instruments/#share) сказано, что признак внебиржевой бумаги, это поле `otc_flag`

![image](https://github.com/user-attachments/assets/947a46d0-033c-42f0-a9cf-63440b8c936e)

Тем не менее, API отдаёт значение false в этом поле, из-за чего я, как пользователь API, без своего ведома, оплачиваю огромную комиссию.

Примеры: TGKJ, NOMP, NOMPP

Запрос
```
curl -X 'POST' \
  'https://invest-public-api.tinkoff.ru/rest/tinkoff.public.invest.api.contract.v1.InstrumentsService/ShareBy' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer мойтокен' \
  -H 'Content-Type: application/json' \
  -d '{
  "idType": "INSTRUMENT_ID_TYPE_FIGI",
  "classCode": "MTQR",
  "id": "TCS00A0F61T7"
}'
```

Ответ
```
{
  "instrument": {
    "figi": "TCS00A0F61T7",
    "ticker": "TGKJ",
    "classCode": "MTQR",
    "isin": "RU000A0F61T7",
    "lot": 1,
    "currency": "rub",
    "shortEnabledFlag": false,
    "name": "Форвард Энерго",
    "exchange": "otc_ncc",
    "ipoDate": "2005-09-20T00:00:00Z",
    "issueSize": "880387078",
    "countryOfRisk": "RU",
    "countryOfRiskName": "Российская Федерация",
    "sector": "energy",
    "issueSizePlan": "273738951",
    "nominal": {
      "currency": "rub",
      "units": "1",
      "nano": 660000000
    },
    "tradingStatus": "SECURITY_TRADING_STATUS_NORMAL_TRADING",
    "otcFlag": false,
    "buyAvailableFlag": true,
    "sellAvailableFlag": true,
    "divYieldFlag": false,
    "shareType": "SHARE_TYPE_COMMON",
    "minPriceIncrement": {
      "units": "0",
      "nano": 10000000
    },
    "apiTradeAvailableFlag": true,
    "uid": "0102d253-5095-499c-934e-5a5fd6fce00d",
    "realExchange": "REAL_EXCHANGE_MOEX",
    "positionUid": "0bca5962-b96e-417b-99dd-d45d538c15b2",
    "assetUid": "3941418c-804d-4f5f-8da5-c1867b83e6d7",
    "instrumentExchange": "INSTRUMENT_EXCHANGE_UNSPECIFIED",
    "forIisFlag": true,
    "forQualInvestorFlag": true,
    "weekendFlag": false,
    "blockedTcaFlag": false,
    "liquidityFlag": false,
    "first1minCandleDate": "2023-04-26T07:37:00Z",
    "first1dayCandleDate": "2023-04-26T07:00:00Z",
    "brand": {
      "logoName": "RU000A0F61T7.png",
      "logoBaseColor": "#000000",
      "textColor": "#ffffff"
    }
  }
}
```

То что TGKJ это внебиржевая бумага, отображается в терминале
![image](https://github.com/user-attachments/assets/6d338fc2-632f-4c75-9c9f-d2222a487528)

Также эта бумага перечислена в [документации](https://www.tbank.ru/invest/help/educate/otc/about/rus-shares/?internal_source=app_inv/) о внебиржевых бумагах, в списке таких бумаг.
![image](https://github.com/user-attachments/assets/3b0351b5-3321-4af4-83d7-126d86b2cdc1)

Прошу исправить ошибку, либо указать в документации API иной способ получить истинное значение признака.

**Comment by p977ac** [comment]
Бумаги, торгуемые на бирже во внебиржевом режиме торгов можно определить по признаку площадки: "exchange": "otc_ncc".

**Comment by NikolayXHD** [comment]
Спасибо за пояснение. Будет исправление в документации?

**Comment by p977ac** [comment]
Да, нужно будет как-то подправить. otc_flag в последнее время утратил актуальность, и сейчас уже нет торгуемых инструментов на любой площадке с otc_flag=true. У инструментов торговавших когда-то там он еще может стоять, но если торги по инструменту возобновляются, то флаг снимается.

**Comment by NikolayXHD** [comment]
Наверное лучше оставить открытой, может кому-то поможет, пока в документации не исправлено

**Comment by olsh** [comment]
Неплохо было бы еще это сделать
https://github.com/RussianInvestments/investAPI/issues/152#issuecomment-2262378185

**Comment by NikolayXHD** [comment]
Увидел исправление в документации. Всё ещё не написано, как фильтровать внебиржевые бумаги, это будет добавлено?

> Бумаги, торгуемые на бирже во внебиржевом режиме торгов можно определить по признаку площадки: "exchange": "otc_ncc".

**Comment by volkov-invest** [comment]
Спасибо за PR
