### ISSUE TITLE
WebSocket-авторизация через браузер

### ISSUE THREAD

**Issue by Igora0** [RussianInvestments/investAPI#159]
Здравствуйте.

Где можно посмотреть пример кода?
То, что пишу - не работает..

const socket 	= new WebSocket('wss://invest-public-api.tinkoff.ru/ws/', 'protocol', {	headers:  
   	{'Authorization': 'Bearer *token'} } );

**Comment by volkov-invest** [comment]
Добрый день, для браузера подставлять в `Web-Socket-Protocol: json, *token`
документация https://russianinvestments.github.io/investAPI/ws/
пример: https://github.com/RussianInvestments/investAPI/blob/main/src/docs/ws/websock/store.js#L107
