### ISSUE TITLE
Некоррекная цена последних сделок по ФСК РосСети

### ISSUE THREAD

**Issue by Igora0** [RussianInvestments/investAPI#160]
Ответ выглядит так:
{

"lastPrices": [

{

"figi": "88e130e8-5b68-4b05-b9ae-baf32f5a3f21",

"instrumentUid": "",

"lastPriceType": "LAST_PRICE_UNSPECIFIED"

},

{

"figi": "BBG00475JZZ6",

"price": {

"units": "0",

"nano": 75680000

},

"time": "2024-10-28T11:03:44Z",

"instrumentUid": "88e130e8-5b68-4b05-b9ae-baf32f5a3f21",

"lastPriceType": "LAST_PRICE_EXCHANGE"

}

]

}

Но должно быть не ""nano": 75680000" , а ""nano": 075680000" ...

**Comment by p977ac** [comment]
Лидирующие нули в nano не передаются, подробнее с примерами написано на [странице](https://russianinvestments.github.io/investAPI/faq_custom_types/).
