### ISSUE TITLE
Непонятное значение ГО для фьючерса SFIN-12.24 ЭсЭфАй

### ISSUE THREAD

**Issue by Igora0** [RussianInvestments/investAPI#161]
Запрашиваю размер ГО для uid e344491e-aa1f-429d-8756-cdb0980535ce  (SFIN-12.24 ЭсЭфАй)
Получаю ответ:
{

"initialMarginOnBuy": {

"currency": "rub",

"units": "670",

"nano": 600000000

},

"initialMarginOnSell": {

"currency": "rub",

"units": "687",

"nano": 840000000

},

"minPriceIncrement": {

"units": "0",

"nano": 200000000

},

"minPriceIncrementAmount": {

"units": "0",

"nano": 200000000

}

}

В тоже время в терминале вижу другое значение ГО: (359.86 рублей)
![image](https://github.com/user-attachments/assets/8954f14b-57e6-4d8b-8112-1aae151e3ea2)

Что я делаю не так? Почему значения ГО разные?

**Comment by p977ac** [comment]
В initialMarginOnBuy\Sell передаются биржевые значения ГО, брокер блокирует средства исходя из ставок риска, детали на  [странице](https://russianinvestments.github.io/investAPI/head-instruments/#_5).
