### ISSUE TITLE
Поле Currency возвращает RUB на активы из US. Как так? биржа SPB

### ISSUE THREAD

**Issue by JohnDarkElf** [RussianInvestments/investAPI#165]
Раньше фильтр стоял на активы по Currency а теперь открываю и у меня весь список активов. нашел в чем причина. собственно что изменилось?

**Comment by volkov-invest** [comment]
На этой неделе в Т стали доступны торги заблокированными бумагами на SPB ( класскод SPBRU_OTC) в рублях.
Сейчас в API они доступны, но сегодня закроем их для клиентов API (возможность торговать в других интерфейсах останется).
