### ISSUE TITLE
Получить дату оферты облигации

### ISSUE THREAD

**Issue by p977ac** [RussianInvestments/investAPI#25]
По обращению от @OdCheban

Спасибо, что в API добавили облигации, но без даты оферты (если она есть) - это почти бесполезно 😞
как скоро получится добавить?
можно конечно ориентироваться на дату последнего известного купона - но иногда нужна дата оферты
image
к примеру ГТЛК выпуск 7, получить дату оферты "18.01.2023";

![image](https://github.com/RussianInvestments/investAPI/assets/142778593/c8d07b81-fed3-4983-a3b9-44ab13346df1)

**Комментарии**

1. Поднимаю данный вопрос заново. Данная таска висит уже более полу года!
Нужна дата оферты!
Реализуйте пожалуйста как можно скорее!
3. можно информацию по срокам, пожалуйста. Прошел почти целый год
2. Поддерживаю, это поле очень нужно, добавьте, пожалуйста

**Comment by ivan-volnov** [comment]
Up

**Comment by ivan-volnov** [comment]
Ура! Спасибо!
