### ISSUE TITLE
Методы для работы со скринером

### ISSUE THREAD

**Issue by p977ac** [RussianInvestments/investAPI#33]
По обращению от @olsh

Было бы неплохо, иметь возможность хотя бы получать акции по заранее созданным скринерам.
А в дальнейшем, иметь возможность управлять скринерами через API.

**Комментарии:**

1. Добрый день, API в первую очередь ориентировано на выгрузку первичных данных, на основе которых пользователи смогут написать скринер самостоятельно. Интеграцию со скриннером в API добавим, но с низким приоритетом.
2. А есть уже возможность получить показатели по компании с помощью API? P/E, P/S, объемы?
3. +1, очень хотелось бы получать фундаментальные показатели и расписания отчётов через API.

**Comment by p977ac** [comment]
@olsh,
фундаментальные показатели добавили https://russianinvestments.github.io/investAPI/instruments/#getassetfundamentals
Отчеты в ближайших планах, скринер на текущий момент делать не планируем.

**Comment by olsh** [comment]
@p977ac проверил работу фундаментальных данных, и что-то у меня не сходится.

На скриншоте код который получает несколько фундаментальных показателей по акции `AA` (взял ее для примера, другие не смотрел).
![image](https://github.com/RussianInvestments/investAPI/assets/3613592/eb74e791-6123-4c1c-98f6-e4e7badcdba8)

В мобильном приложении цифры абсолютно другие PE, ROE и ROA там отрицательные. Debt +/- сходится, но в приложении он 29.71%.

**Comment by p977ac** [comment]
@olsh
1. Искать нужно не по UID инструмента, а по UID ассета(найти можно из метода getAssets), для АА: 148bccad-d958-4350-9528-784cd3dfff15
2. Но данные от скриншота все равно отличаются. На каком сайте смотрите? Предположу, что разные провайдеры данных, где-то неактуальная информация.

**Comment by olsh** [comment]
1. Проверю, спасибо, можете тогда с точки зрения API пояснить разницу между инструментом и ассетом?
2. На сайте Тинькофф.

**Comment by p977ac** [comment]
Не совсем так. Asset - актив (акция, облигация и т.д.), он может торговаться на разных биржах, это будут уже разные инструменты, или не торговаться вообще. Фундаментальные показатели относятся к компании, которая выпустила активы, если актив торгуется на разных биржах, то у разных инструментов будут одинаковые показатели. Наличие или отсутствие показателей зависит от того, публикует ли компания отчетности, предоставляет ли их наш провайдер и от других факторов.

Возможность получать показатели по Instrument UID мы рассмотрим.

**Comment by olsh** [comment]
Спасибо за объяснение.

Вот еще что нашел:

Все показатели которые касаются Free Cash Flow равны нулю. Проверял на выборке из 10 тикеров, в том числе на AAPL, где FCF точно не нулевой.
FCF AAPL можно посмотреть, например, тут.
https://finviz.com/quote.ashx?t=AAPL&p=d
Или тут
https://finance.yahoo.com/quote/AAPL/cash-flow?p=AAPL

**Comment by p977ac** [comment]
Это особенности реализации нашего gRPC. API возвращает все параметры контракта, если значение строковое, то, в случае отсутствия, это будет пустая строка "", если числовое, то 0. Могу порекомендовать для данного метода 0 считать отсутствием значения (реальные 0 достаточно маловероятно). FCF сейчас отсутствует, как и ряд других параметров. Но наши коллеги работают с провайдерами, по наполнению контента, надеюсь, что ситуации улучшится.

**Comment by olsh** [comment]
Спасибо за ответ!

> Могу порекомендовать для данного метода 0 считать отсутствием значения (реальные 0 достаточно маловероятно).

Опять же, мы рассматриваем частный случай, есть и другие показатели где 0 это не такое уж и редкое явление. Считаю что реализация не очень удачная и требует доработки. Предложил бы использовать не примитивы, а структуру в которой бы было состояние (есть значение/нет значения) и само значение или уж хотя бы nullable типы.

**Comment by olsh** [comment]
> другие показатели где 0 это не такое уж и редкое явление

Хороший пример `DividendYieldDailyTtm`. У многих компаний нет дивидендов, вот API вернул 0. Это означает что нет дивидендов или нет данных?

**Comment by batal131** [comment]
А какие есть ограничения у getassetfundamentals?
По одному ассету - все ок. Как только пытаюсь получить по ~150 кидает InvalidArgument (30091).
(получаю через C# SDK)

**Comment by p977ac** [comment]
> А какие есть ограничения у getassetfundamentals? По одному ассету - все ок. Как только пытаюсь получить по ~150 кидает InvalidArgument (30091). (получаю через C# SDK)
Ошибка 30091 - Количество инструментов не может превышать 100, подробнее про коды можно почитать тут: https://russianinvestments.github.io/investAPI/errors/
Про ограничение добавим в описание метода

**Comment by p977ac** [comment]
> > другие показатели где 0 это не такое уж и редкое явление
> 
> Хороший пример `dividend_yield_daily_ttm`. У многих компаний нет дивидендов, вот API вернул 0. Это означает что нет дивидендов или нет данных?

Для избегания ошибок рекомендую 0 считать отсутствием данных

**Comment by olsh** [comment]
> Для избегания ошибок рекомендую 0 считать отсутствием данных

Это понятно, _придется_ так делать. Но согласитесь, что дизайн API не очень удачный и было бы неплохо улучшить его?

**Comment by p977ac** [comment]
расписания отчетов добавлены
