### ISSUE TITLE
Отсутствие валидации minPriceIncrement [bug]

### ISSUE THREAD

**Issue by p977ac** [RussianInvestments/investAPI#34]
По обращению от @betslus1

Пример:
figi: BBG00HNGJ8K1
ticker: MOEX:RU000A0ZYA66
minPriceIncrement для него 0.012 ( облигация, номинал 120 )
TestCase : postOrder(price = {units: 120, nano: 40000000})

Долгое время не замечал, что отправляя цену в рублях (так принято для облигаций для метода postOrder) например 120.40 (невалидная цена, в силу неверного округления на моей стороне 120.36) не возвращалось ошибки валидации по minPriceIncrement, при этом на биржу уходило по 100.04 x 0.012 x 100 = 120.48.

Это в свою очередь вызвало цикличное перевыставление цены (робот считал что на бирже цена не соответствует нужной ему цене) и существенное снижение success ratio и лишнее использование лимитов.

Должна возвращаться ошибка валидации несоответствия минимальному шагу

**Comment by volkov-invest** [comment]
В связи с округлением цены до ближайшего minPriceIncrement в лучшую для клиента сторону, в валидации нет необходимости.
