### ISSUE TITLE
Новые операции при дивидендах на карту

### ISSUE THREAD

**Issue by p977ac** [RussianInvestments/investAPI#55]
По обращению от @borrispu

В случае ИИС возможна выплата дивидендов на карту вместо брокерского счета. Из-за этого не сходится сумма на брокерском счете по итогу операций. Дело в том, что налоги DIVIDEND_TAX удерживаются не с брокерского счета, а с карты, хотя по операции это определить невозможно. Тогда сделайте, пожалуйста, для таких кейсов отдельные операции DIVIDEND_TAX_EXT/DIVIDEND_TAX_PROGRESSIVE_EXT вместо DIVIDEND_TAX/DIVIDEND_TAX_PROGRESSIVE, чтобы было понятно, что налоги списываются не с брокерского счета, а с карты.

Пример операции:
brokerAccountId = "2215055787"
id = "2207454676"
date = "2023-06-15T14:01:09Z"
type = "OPERATION_TYPE_DIVIDEND_TAX"
description = "Удержание налога по дивидендам"

По факту это налог с дивидендов ЛУКОЙЛ, удержанный с карты, а не со счета ИИС.

Типов операции OPERATION_TYPE_DIVIDEND_TAX_EXT/DIVIDEND_TAX_PROGRESSIVE_EXT сейчас вообще нет в документации https://RussianInvestments.github.io/investAPI/operations/#operationtype.

**Comment by p977ac** [comment]
@borrispu в случае выплаты дивидендов налоги удерживаются в депозитарии и с брокерским счетом этот процесс не связан. А на брокерский счет позже зачисляется сумма за вычетом дивидендов.
Операции предоставляются в API для наглядности.

Налоги от дивидендов, в отличие от купонов,  - отдельный тип налогов, который законодательством отделяется от налога с доходов по операциям с ценными бумагами. 
В случае с ИИС списать налог с брокерского счета невозможно технически, любой удержание денег со счета приведет к закрытию ИИС.

**Comment by borrispu** [comment]
> @borrispu в случае выплаты дивидендов налоги удерживаются в депозитарии и с брокерским счетом этот процесс не связан. А на брокерский счет позже зачисляется сумма за вычетом дивидендов. Операции предоставляются в API для наглядности.
> 
> Налоги от дивидендов, в отличие от купонов, - отдельный тип налогов, который законодательством отделяется от налога с доходов по операциям с ценными бумагами. В случае с ИИС списать налог с брокерского счета невозможно технически, любой удержание денег со счета приведет к закрытию ИИС.

Спасибо за важную информацию. К сожалению, она не относится к сути проблемы. Попробую выразиться яснее. Сейчас в операцию OPERATION_TYPE_DIVIDEND_TAX (Удержание налога по дивидендам) попадают и те налоги, которые удержаны с суммы, выплаченной на брокерский счет, и те налоги, которые удержаны с суммы, выплаченной на карту. Но так как операции по сумме дивидендов (OPERATION_TYPE_DIVIDEND или OPERATION_TYPE_DIV_EXT) никак нельзя соотнести с операциями по налогам, не получается на основании предоставленной API информации правильно определить изменение суммы на брокерском счете. Потому что в одном случае налоги нужно вычесть, а в другом не нужно. Попробую решить самостоятельно, на своей стороне...
