### ISSUE TITLE
свечной стрим MarketData  в интервале SUBSCRIPTION_INTERVAL_WEEK поставляет некорректные свечи

### ISSUE THREAD

**Issue by nonamegithub** [RussianInvestments/investAPI#69]
![image](https://github.com/RussianInvestments/investAPI/assets/69071220/337fc855-cd78-4d17-bf61-fbc3724f5d49)
1696118400 = Sun, **01** Oct 2023 00:00:00 GMT
Или месячные свечи идут вместо недельных, или начало недели разработчики отсчитывают по календарной системе США,  что наталкивает на определенные выводы...

**Comment by p977ac** [comment]
исправлено
