### ISSUE TITLE
свечной стрим MarketData в интервале SUBSCRIPTION_INTERVAL_MONTH поставляет некорректные свечи

### ISSUE THREAD

**Issue by nonamegithub** [RussianInvestments/investAPI#70]
![image](https://github.com/RussianInvestments/investAPI/assets/69071220/acf31457-e368-4dbf-b36f-4e2eaea73d7e)
Свеча месячная - объем недельный

**Comment by p977ac** [comment]
Добрый день. Проблема решена.
![candle_volumes](https://github.com/RussianInvestments/investAPI/assets/142778593/1aaa276b-36f6-4466-9f70-98a96df0c5df)
