### ISSUE TITLE
Использование ключа идемпотентности для стоп-заявок

### ISSUE THREAD

**Issue by nonamegithub** [RussianInvestments/investAPI#74]
Прошу реализовать использование ключа  [идемпотентности](https://russianinvestments.github.io/investAPI/head-orders/#_6) также и для стоп-заявок - не нужны будут танцы с бубном для их дальнейшего отслеживания после размещения.
Но это еще не все: после трансформации стоп-заявки в лимитную/рыночную необходимо, чтобы поле order_request_id лимитной/рыночной унаследовало значение stop_order_id (ну или значение еще нереализованного поля stop_order_request_id) стоп-заявки. Так появится возможность отследить весь жизненный цикл стоп-заявок, в чем давно уже назрела необходимость [("сквозная нумерацию заявок")](https://github.com/Tinkoff/investAPI/issues/388#issuecomment-1501156590)

**Comment by nonamegithub** [comment]
Ау, есть кто-живой??? За идею ухватились, как я понял, суда по соответствующим изменениям в релизах InvestAPI, а обсудить религия не позволяет? Не стесняйтесь, разжую подробно для тугих. Вдруг криво слепите в итоге

**Comment by nonamegithub** [comment]
Ну правильно, лучше молчите, раз накосячили. Кого будете наказывать у себя за кривой нейминг, может ["аналитика"](https://github.com/RussianInvestments/investAPI/issues/106#issuecomment-2040233405), которому не стыдно за свою работу, а?
Уместно использовать имена "order_id" и "order_request_id" для [стоп заявок](https://russianinvestments.github.io/investAPI/stoporders/#poststoporderrequest), а? Я как вам предлагал в [issue](https://github.com/RussianInvestments/investAPI/issues/74#issue-1972171724)???

**Comment by nonamegithub** [comment]
Где, в конце концов, [подобное описание](https://russianinvestments.github.io/investAPI/faq_orders/#order_id-postorder_1) для [PostStopOrder](https://russianinvestments.github.io/investAPI/example/#poststoporder-), и объяснение своеобразного нейминга, в контексте связи между PostStopOrder и PostOrder?
А теперь вишенка на торте! После которой любой, имеющий хоть каплю совести, специалист сразу возьмет лист чистой бумаги и обходной лист в бухгалтерии.
[Цитата:](https://russianinvestments.github.io/investAPI/faq_orders/#4.2) "В данный момент order_id используется исключительно как ключ идемпотентности и не "прокидывается" в другие сущности системы. **Есть планы в будущем отображать переданный ключ в операциях**."  То есть, Банк планирует добавить дополнительное поле в операции и это, как я понимаю, не приведет ни к какой ["потери производительности"](https://github.com/RussianInvestments/investAPI/issues/108#issuecomment-2042651391), в отличие от [добавления поля UpdatedAt/ModifiedAt](https://github.com/RussianInvestments/investAPI/issues/108#issue-2230554157)?

Тушите свет! Аналитику, как я думаю, по прежнему [не стыдно](https://github.com/RussianInvestments/investAPI/issues/106#issuecomment-2040233405), зато стыдно мне. За аналитика.

**Comment by p977ac** [comment]
Сервис стоп ордеров не поддерживает ключ идемпотентности

**Comment by nonamegithub** [comment]
[Документация по Invest API говорит об обратном. Или ей нельзя верить?](https://russianinvestments.github.io/investAPI/stoporders/#poststoporderrequest)

**Comment by p977ac** [comment]
> [Документация по Invest API говорит об обратном. Или ей нельзя верить?](https://russianinvestments.github.io/investAPI/stoporders/#poststoporderrequest)

Ключ идемпотентности в стоп ордерах хранится и валидируется в кеше с коротким сроком жизни. Он может использоваться для защиты от случайного повторного выставления стоп заявки, но не подходит для отслеживания.

**Comment by nonamegithub** [comment]
Эх, Константин... Вижу и здесь команда не поняла моей идеи... Я ведь предлагал очень простую и понятную вещь: помимо добавления ключа идемпотентности в стоп-заявки, я предлагал использовать в дальнейшем этот ключ в качестве order_id порождаемой стоп-заявкой лимитной или рыночной заявки. В итоге, order_request_id лимитной или рыночной заявки, полученный через [GetOrders()](https://russianinvestments.github.io/investAPI/orders/#getorders) или через [OrderState()](https://russianinvestments.github.io/investAPI/orders/#orderstate), четко укажет пользователю Invest API на "родителя" заявки, если таковой имеется - ключ идемпотентности стоп-заявки станет идентификатором для "сквозной" нумерации стоп-заявок и порождаемых ими лимитных или рыночных заявок.
Пусть уже хоть кто-нибудь начнет торговать в вашей команде исключительно через Invest API - начнем в таком случае разговаривать на одном языке.

**Comment by p977ac** [comment]
> Эх, Константин... Вижу и здесь команда не поняла моей идеи... 
Пусть уже хоть кто-нибудь начнет торговать в вашей команде исключительно через Invest API - начнем в таком случае разговаривать на одном языке.

Это вы отказываетесь понимать. У вас, видимо, отсутствует или совсем небольшой опыт работы в крупных компаниях. Вы отказываетесь слушать и взаимодействовать на уровне диалога. 
Вам уже несколько раз объясняли, что такое АПИ, но вы все равно не понимаете.
Расскажу ещё раз: Апи - это Интерфейс, прослойка, фасад к брокерский сервисам. Когда я говорил, что ключ не реализован в сервисе стоп-ордеров, это означало, что функционал недоступен в общеброкерском сервисе, а не в Апи и методах Апи, и дорабатывать его коллеги не планируют.
Вы написали запрос, мы зашли к коллегам, получили ответ. У коллег свой беклог, свои задачи. Если у вас есть возможности повлиять на приоритезацию их разработки - действуйте, у нас такой возможности нет. Надеюсь, вы понимаете, что под действием я подразумеваю не сотрясение воздуха на github.

**Comment by nonamegithub** [comment]
> Вы написали запрос, мы зашли к коллегам, получили ответ. У коллег свой беклог, свои задачи. Если у вас есть возможности повлиять на приоритезацию их разработки - действуйте, у нас такой возможности нет.

Позиция обыкновенного приспособленца. И коллеги у вас такие же, судя по всему. Работы конь не валялся и у тех и у других, а корчат из себя корифеев IT. Позорище. Дальнейшее общение с тобой считаю нецелесообразным.
