### ISSUE TITLE
Выставления торгового поручения

### ISSUE THREAD

**Issue by Airat102vb** [RussianInvestments/investAPI#78]
Здравствуйте, периодически при выставлении торгового поручения, получаю ошибку

`Exception in thread "main" java.lang.RuntimeException: ru.tinkoff.piapi.core.exception.ApiRuntimeException: Ошибка метода выставления торгового поручения. Подробнее в тексте ошибки.`
Больши ни какой информации нет, нет и request_id.

У меня эта операция отоброжается в вебе в 07 декабря 2023 г., 17:47 (582,2 ₽) как отмененная.
Можно как то получить доп информацию, по какой причине падение было?

**Comment by p977ac** [comment]
Добрый день.
@Airat102vb, нужны детали операции: ИД ордера, ИД аккаунта, trace-ID, который возвращается в заголовка ответа или какой-то иной идентификатор, который бы позволил определить вашу заявку.
