### ISSUE TITLE
Работа со стримами

### ISSUE THREAD

**Issue by AndyPary** [RussianInvestments/investAPI#79]
Добрый день!

Я новичок в python и знания только приобретаю, поэтому заранее прошу прощения если вопрос покажется странным...

Есть два стрима.  Первый стрим - стрим портфолио. Второй стрим - стрим трейдов по позициям из портфолио. В идеале, позиции в портфеле меняются (добавляются или убывают), соответственно стрим по трейдам должен работать только с тем, что сейчас в портфеле. 
Допускаю, что надо перезапускать стрим по трейдам каждый раз, когда меняется конфигурация портфеля. Но как сообщить стриму, что в портфеле произошли изменения и что надо перезапускаться - голову сломал.
Стрим по трейдам работает только с первоначальной конфигурацией портфеля.
Прошу помочь куда смотреть, что изучать. 

Ниже код, который работает не так

~~~
with Client(TOKEN) as client:

    x = client.operations.get_portfolio(account_id=acc_id)
    xx = x.positions
    list_figi = []

    for ni in xx:
        if ni.instrument_type =="currency":
            pass
        else:
            list_figi.append(ni.figi)
    print(list_figi)

async def start():
    with Client(TOKEN) as client:
        a = client.operations_stream.portfolio_stream(accounts=[acc_id])

        for i in a:
            zz = i.portfolio
            if zz != None:
                list_figi2 = []
                for u in zz.positions:

                    if u.instrument_type == "currency":
                        continue
                    list_figi2.append(u.figi)
                f = list_figi2
                print(f"list_figi2 {f}")
                await r(f)

            else:
                f = list_figi
                print(f"list_figi {f}")
                await r(f)

async def r(f):

    async with AsyncClient(TOKEN) as client:
        market_data_stream: AsyncMarketDataStreamManager = client.create_market_data_stream()
        market_data_stream.trades.subscribe([TradeInstrument(figi= figi) for figi in f])

        async for marketdata in market_data_stream:
            a = marketdata.trade
            if (a == None):
                print(f"a: {a}")
            else:
                print(a.figi, a.price.units + a.price.nano / 1000000000)
                await asyncio.sleep(0.1)

async def main():
    task1 = asyncio.create_task(start())
    await task1
~~~

**Comment by AndyPary** [comment]
В итоге решил задачу по другому...
Тем не менее эта задача осталась для меня не решенной. Если у кого-то будет возможность, прошу поделиться знаниями.

**Comment by volkov-invest** [comment]
>Допускаю, что надо перезапускать стрим по трейдам каждый раз, когда меняется конфигурация портфеля

Нет, стрим Вы создаете один раз, а далее - по факту изменения позиций в портфолио - только подписываться (либо отписываться) на нужные данные в уже существующем стриме.
