### ISSUE TITLE
Дайте какой-нибудь рабочий код на Python по работе со стримом.

### ISSUE THREAD

**Issue by KozlovAleksei** [RussianInvestments/investAPI#81]
Что-то поигрался с SDK и получается только делать разовые запросы. Хотелось бы пример на Python в одну страничку, чтобы было наглядно в консоли видно как работает стрим. В частности актуально по открытым позициям портфеля. А то не понятно как реализовывать, нужна асинхронность или без неё можно обойтись.

**Comment by Dankosik** [comment]
Пример марктет дата стрима скидывали в чате. Если не подпсан - залетай https://t.me/joinchat/VaW05CDzcSdsPULM
Там тебе быстро пример накидают, а пример доступен ниже по ссылке (как раз на днях просили).
https://pastebin.com/yRf9EcqD
