### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'public')

### ISSUE THREAD

**Issue by nonamegithub** [RussianInvestments/investAPI#83]
Что за изменения произошли  в [InvestAPI](https://github.com/RussianInvestments/investAPI), начиная с версии 1.7, из-за которых [SDK для Node JS от betslus1](https://github.com/betslus1/unofficial-tinkoff-invest-api_v2-lazy-sdk-NODEJS) падает с ошибкой, упомянутой в subj?
SDK пока не под подозрением, так как помню упоминания Ал. В-ва о [проблемах с public](https://github.com/protocolbuffers/protobuf/issues/9058), включая  [этот issue](https://github.com/RussianInvestments/investAPI/issues/11).

**Comment by nonamegithub** [comment]
убрал из proto-файлов import  field_behavior.proto, появившийся с 1.7 - взлетело.  может кому поможет.

**Comment by nonamegithub** [comment]
Переоткрыл issue, решил спуску не давать бездельникам. По любому кто-то встрянет на этой проблеме. Оказывается на ветке есть ["аналитик"](https://github.com/RussianInvestments/investAPI/issues/106#issuecomment-2040233405) команды Invest API, ему слово!
Подсказка: "в прото-контрактах добавили разметку опциональными полями proto3"

**Comment by p977ac** [comment]
Развитием и сопровождением неофициальных SDK занимается его разработчик.
