### ISSUE TITLE
Точно "Реализована поддержка торговли лимитными заявками по выходным"?

### ISSUE THREAD

**Issue by nonamegithub** [RussianInvestments/investAPI#84]
Повелся на [анонс](https://github.com/RussianInvestments/investAPI/releases/tag/V1.8) , но при выставлении лимитной заявки получаю: "Tranzakczii nedostupny". Как быть?
Стакан, разумеется полон, торговля, судя по всему, идет...

**Comment by p977ac** [comment]
@nonamegithub, торговля по выходным доступна, но с некоторыми ограничениями. Недоступны рыночные (market) заявки и лимитные заявки с TIME_IN_FORCE = FILL_OR_KILL. Описание на странице с документацией поправим.

**Comment by nonamegithub** [comment]
Потрудитесь объяснить, что вы там опять наколхозили.  [Описание](https://russianinvestments.github.io/investAPI/orders/#timeinforcetype) прочитал, но как я понял, TIME_IN_FORCE это возвращаемое поле, не? И при чем тут оно?

**Comment by nonamegithub** [comment]
и не дай Бог опять две недели будете отвечать - буду звонить Близнюку, чтобы разгонял вашу шарашку.

**Comment by p977ac** [comment]
> Потрудитесь объяснить, что вы там опять наколхозили. [Описание](https://russianinvestments.github.io/investAPI/orders/#timeinforcetype) прочитал, но как я понял, TIME_IN_FORCE это возвращаемое поле, не? И при чем тут оно?

Посмотрите [страницу](https://russianinvestments.github.io/investAPI/weekend_trading/), может быть, станет понятнее. TIME_IN_FORCE - один из передаваемых параметров метода [PostOrder](https://russianinvestments.github.io/investAPI/orders/#postorderrequest). Если не получается выставить ордер в выходные, присылайте детали: номер счета, время, когда выставляли или traceId.

**Comment by nonamegithub** [comment]
Хорошо. Объясните мне тогда, как работают нижеследующие параметры:
**TIME_IN_FORCE_FILL_AND_KILL**  -   Заявка исполнена(возможно частично) и уничтожена
**TIME_IN_FORCE_FILL_OR_KILL**  -  Заявка исполнена полностью или уничтожена, недоступно для срочного рынка и торговли по выходным
Что будет, если я вообще не передаю это поле?

**Comment by p977ac** [comment]
> Хорошо. Объясните мне тогда, как работают нижеследующие параметры: **TIME_IN_FORCE_FILL_AND_KILL** - Заявка исполнена(возможно частично) и уничтожена **TIME_IN_FORCE_FILL_OR_KILL** - Заявка исполнена полностью или уничтожена, недоступно для срочного рынка и торговли по выходным Что будет, если я вообще не передаю это поле?

1. Если не передаете, выставляется обычная лимитная заявка. Она будет отменена(если не исполнится), как правило, по окончанию торговой сессии.
2. FILL_AND_KILL - выставляете лимитную заявку, если в стакане есть предложения по указанной цене, заявка исполнится на размер предложения, а неисполненный кусок будет отменен. Пример, покупаете 10 акций по 5 рублей, в стакане есть предложение 3 акций по 5 рублей. По итогам заявки вы купите 3 акции, а остаток будет отменен (при обычной лимитной заявке осталась бы висеть активная частично исполненная заявка). Если предложений по указанной цене нет, заявка сразу же будет отменена.
3. FILL_OR_KILL - похожий механизм, но заявка будет исполнена только если в стакане есть предложение на весь объем. Для примера выше, заявка исполнится только если в стакане будет предложение 10 акций по цене 5 рублей или лучше. Частичное исполнение не подразумевается. Если в момент подачи заявки невозможно ее полное исполнение, она будет сразу же отменена.

**Comment by nonamegithub** [comment]
Видите как, оказывается. Не все здесь внуки Ванги, чтобы трансформировать в мозгу пару куцых нерусских фраз в такую текстовку.
Выставлял лимитные, без TIME_IN_FORCE. В будние выставляются без проблем, в выходные - с ошибкой "Tranzakczii nedostupny". В следующую субботу кину вам traceId.
Куда делся ваш технический писатель? Его явные недоработки сейчас накаляют ситуацию на ровном месте

**Comment by nonamegithub** [comment]
ларчик просто открывался: "... для ИИС торги на выходных пока не доступны"

**Comment by p977ac** [comment]
Да, для ИИС торговля недоступна, ограничение по всему брокеру. Хорошо, что разобрались.
