### ISSUE TITLE
Отсутствует UID инструмента в запросе GetConsensusForecasts

### ISSUE THREAD

**Issue by olsh** [RussianInvestments/investAPI#86]
По всей видимости, предполагалось, что можно передать Instrument ID в этот метод?
https://russianinvestments.github.io/investAPI/instruments/#getconsensusforecasts
На данный момент варианта, кроме как вытягивать все прогнозы, нет.

**Comment by p977ac** [comment]
@olsh , если честно, на текущий момент не планировали. Кажется, что нет сложности затянуть к себе одним запросом все прогнозы и дальше работать внутри своего приложения, периодически обновляя данные.

**Comment by olsh** [comment]
> Метод получения мнения аналитиков по инструменту

Тогда вопросов нет. Но комментарий выглядит не валидно, раз не планировали

> Кажется, что нет сложности затянуть к себе одним запросом все прогнозы и дальше работать внутри своего приложения, периодически обновляя данные.

Проблемы нет, хоть это и очень спорное решение — вытягивать разом 3671 записей.
