### ISSUE TITLE
Добавить в GetOrderState время отмены ордера

### ISSUE THREAD

**Issue by volkov-invest** [RussianInvestments/investAPI#87]
Для ордеров со статусом CANCELLED/REJECTED добавить поле со временем отмены.

**Comment by belousov-m** [comment]
Изначально есть необходимость различать: кто сделал cancelled, пользователь или система. В идеале хотелось бы видеть например: поле "initiator" с возможными значениями: "system", "user". Что-то подобное

**Comment by p977ac** [comment]
В GetOrderState нет возможности это реализовать. Детализация по операциям с ордерами планируется в рамках стрима, обсуждаемого тут:
https://github.com/RussianInvestments/investAPI/issues/15
