### ISSUE TITLE
Разные positionUid у операций относительно одной акции

### ISSUE THREAD

**Issue by Rosso-corsa** [RussianInvestments/investAPI#93]
Добрый день!

Заметил проблему, что у некоторых позиций positionUid может отличаться.

Пример акций Сбера из InstrumentsService API:
`{'figi': 'TCS109029540', 'ticker': 'SBER', 'classCode': 'SPEQ', 'isin': 'RU0009029540', 'name': 'Сбер Банк', 'positionUid': '41eb2102-5333-4713-bf15-72b204c4bf7b', 'assetUid': '40d89385-a03a-4659-bf4e-d3ecba011782', [...]}`
`{'figi': 'TCS209029540', 'ticker': 'RU0009029540', 'classCode': 'RU0009029540_TNDS', 'isin': 'RU0009029540', 'name': 'Сбер Банк', 'positionUid': '6b6729f2-83cd-4323-8551-45e0bbf41035', 'assetUid': '40d89385-a03a-4659-bf4e-d3ecba011782', [...]}`

Аналогичное расхождение при получении операций по позиции: покупка акций записана с одним positionUid, а получение дивидендов по ним - с другим:
` {'id': '99952196',
  'type': 'Покупка ценных бумаг',
  'assetUid': '40d89385-a03a-4659-bf4e-d3ecba011782',
  'positionUid': '41eb2102-5333-4713-bf15-72b204c4bf7b',
  'instrumentUid': 'e6123145-9665-43e0-8413-cd61b8aa9b13', [...]}`
` {'id': '113457671078',
  'type': 'Выплата дивидендов',
  'assetUid': '40d89385-a03a-4659-bf4e-d3ecba011782',
  'positionUid': '6b6729f2-83cd-4323-8551-45e0bbf41035',
  'instrumentUid': 'e550801b-1eaf-4704-a363-7fc431e2f98c, [...]'}`

Выглядит как баг в системе, поправьте, пожалуйста, или объясните разницу в positionUid.

Расхождение есть не только для Сбера, заметил и на нескольких других позициях.

**Comment by p977ac** [comment]
Добрый день.

@Rosso-corsa, positionUid - это совокупность актива, типа и торговой площадки(биржи). У брокера, действительно, бывают ситуации, когда размещение, выплаты купонов\дивидендов начисляют по positionUid, который не соответствует торгуемому на бирже инструменту. На текущий момент можно разве что ориентироваться на ISIN или assetUid. Поменять идентификаторы невозможно.

**Comment by nonamegithub** [comment]
А вот это уже становится интересным. Мало знать, оказывается,  [как positionUid соотносится с instrumentId.](https://github.com/Tinkoff/investAPI/issues/417) Похоже, что аналогичная схема работает и в отношении assetUid к positionUid. По мне так это явный изъян в архитектуре структуры данных Invest API.

**Comment by p977ac** [comment]
Справочник хранится и ведется не в API, он единый для брокера. В разные годы у команды справочника были, видимо, разные подходы к структуре, в итоге имеем что есть.

**Comment by volkov-invest** [comment]
Действительно есть подобные расхождения по positionUid. Как правильно заметил @p977ac - на стороне API такое поправить не получится. Рекомендуем сопоставлять подобные операции по assetUid - он  одинаковый.

**Comment by Rosso-corsa** [comment]
1. Про assetUid
 
> Рекомендуем сопоставлять подобные операции по assetUid

Согласно [документации](https://tinkoff.github.io/investAPI/faq_identification/): _"актив - это по сути работающая на финансовом рынке компания, являющаяся эмитентом ценных бумаг. Примером актива может быть например Сбербанк [...] Идентификатор актива - это asset_uid"_.

Если assetUid - это id компании, то поле не годится для выделения всех транзакций относительно одного конкретного выпуска облигаций. Т.к., например, у компании может быть много выпусков. Однако сейчас в примерах ответа сервера я вижу, что у разных выпусков облигаций одной компании assetUid разный. 

Так где тогда ошибка - в определении assetUid в доке или в текущих ответах сервера?

2.  Заметил ещё странное поведение - у транзакций positionUid может вообще меняться. 

Если при заведении тикета у транзакции с id `113457671078` positionUid был `41eb2102-5333-4713-bf15-72b204c4bf7b`, то теперь `3fee9888-c49d-4b9a-bbc7-3be6e49128cf` (и он всё равно отличается от  positionUid в других транзакциях по тем же акциям.
С чем связано такое поведение (изменение positionUid)?

**Comment by p977ac** [comment]
> 1. Про assetUid
> 
> > Рекомендуем сопоставлять подобные операции по assetUid
> 
> Согласно [документации](https://tinkoff.github.io/investAPI/faq_identification/): _"актив - это по сути работающая на финансовом рынке компания, являющаяся эмитентом ценных бумаг. Примером актива может быть например Сбербанк [...] Идентификатор актива - это asset_uid"_.
> 
> Если assetUid - это id компании, то поле не годится для выделения всех транзакций относительно одного конкретного выпуска облигаций. Т.к., например, у компании может быть много выпусков. Однако сейчас в примерах ответа сервера я вижу, что у разных выпусков облигаций одной компании assetUid разный.
> 
> Так где тогда ошибка - в определении assetUid в доке или в текущих ответах сервера?
> 
> 2. Заметил ещё странное поведение - у транзакций positionUid может вообще меняться.
> 
> Если при заведении тикета у транзакции с id `113457671078` positionUid был `41eb2102-5333-4713-bf15-72b204c4bf7b`, то теперь `3fee9888-c49d-4b9a-bbc7-3be6e49128cf` (и он всё равно отличается от positionUid в других транзакциях по тем же акциям. С чем связано такое поведение (изменение positionUid)?

1. [Документацию](https://russianinvestments.github.io/investAPI/faq_identification/#_2) некоторое время назад поправили, у вас старая ссылка. Asset_uid - это идентификатор актива (акции, облигации и т.д.).
2. positionUid - может меняться в результате корпоративных действий. В операциях размещения, выплатах купонов\дивидендов positionUid может отличаться от идентификатора инструмента в портфеле. Используйте assetUid.
