### ISSUE TITLE
Проблема с лимитами tinkoff.public.invest.api.contract.v1.MarketDataStreamService/MarketDataStream

### ISSUE THREAD

**Issue by nonamegithub** [RussianInvestments/investAPI#94]
["Улучшена схема работы с лимитами по стримам, теперь не надо ждать некоторое время в случае неожиданного дисконнекта стримов"](https://github.com/RussianInvestments/investAPI/releases/tag/v1.9) - не соответствует действительности. Обкатывайте, смотрите в чем проблема ,прежде чем заявлять. Не думаю, что я оказался тем "счастливчиком", у кого это не работает.
Пример: по данным tinkoff.public.invest.api.contract.v1.MarketDataStreamService/MarketDataStream: limit - 4, open - 0, но по факту могу создать лишь один стрим. При созданию второго ловлю Error: 8 RESOURCE_EXHAUSTED: 80004. 
Причем не важно, через gGRPC или Websocket - ситуация аналогичная. Так происходит не всегда, но тем не менее...

**Comment by nonamegithub** [comment]
важное дополнение: такое происходит только с MarketData стримами. С Portfolio, Positions и Trades не замечал подобного

**Comment by nonamegithub** [comment]
А вот и объяснение нашлось: если нет подписок в стриме, то он закрывается спустя пару минут с "Error: 8 RESOURCE_EXHAUSTED: 80004". Не благодарите!
Насколько корректен такой алгоритм работы стрима - большой вопрос

**Comment by nonamegithub** [comment]
если уж закрываете пустой стрим, то делайте это с внятной диагностикой типа "... due inactivity"

**Comment by volkov-invest** [comment]
Добрый день, 

>то делайте это с внятной диагностикой типа "... due inactivity"

именно для этих целей новый код 80004 и был введен
